(function(){var f=true,i=null,k=false,ba=this;function ca(a,b,c){a=a.split(".");c=c||ba;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)if(!a.length&&b!==undefined)c[d]=b;else c=c[d]?c[d]:c[d]={}}var m=Date.now||function(){return+new Date};var da,ea,fa=[],ga={},ha=i;function ia(){var a=m();fa.forEach(function(b,c){if(da&&!b.Bb&&!(ha&&(!b.name||ha.indexOf(b.name)===-1))&&!(a-b.ab<=b.Vb)){b.ab=a;b.pb-=1;if(b.pb<=0&&(!b.wb||b.pb<0)){ja(fa,c);delete ga[b.name];if(b.wb)return}b.Ub.apply(b.$b,b.Nb)}});fa.length||ka()}function la(a,b,c,d,e,g,h){var o=m(),l=g?ga[g]:i;if(!l){l={Ub:a,name:g,$b:h,ab:e?-Infinity:o};fa.push(l);g&&(ga[g]=l)}l.Nb=d||[];l.pb=c;l.Vb=Math.max(b,25);l.wb=e;l.Bb=k;da||(da=window.setInterval(ia,25))}
function ma(a,b,c,d,e){la(a,b,1,c,k,d,e)}function na(a,b,c){la(a,100,Infinity,b,k,c,void 0)}function oa(a,b,c,d){la(a,0,1,b,k,c,d)}function pa(a,b){ha=a;b&&(ea=setTimeout(qa,b))}function qa(){ha=i;if(ea){window.clearTimeout(ea);ea=i}}function ra(a){delete ga[a];fa.forEach(function(b,c){if(b.name===a){ja(fa,c);b.Bb=f}})}function ka(){da&&window.clearInterval(da);qa();da=i;fa=[];ga={}};m();if(!Array.prototype.forEach)Array.prototype.forEach=function(a,b){for(var c=0,d=this.length;c<d;c+=1)c in this&&a.call(b,this[c],c,this)};if(!Array.prototype.some)Array.prototype.some=function(a,b){for(var c=0,d=this.length;c<d;c+=1)if(c in this&&a.call(b,this[c],c,this))return f;return k};if(!Array.prototype.every)Array.prototype.every=function(a,b){for(var c=0,d=this.length;c<d;c+=1)if(c in this&&!a.call(b,this[c],c,this))return k;return f};
if(!Array.prototype.map)Array.prototype.map=function(a,b){for(var c=0,d=this.length,e=[];c<d;c+=1)c in this&&(e[c]=a.call(b,this[c],c,this));return e};if(!Array.prototype.filter)Array.prototype.filter=function(a,b){for(var c=0,d,e=this.length,g=[];c<e;c+=1)if(c in this){d=this[c];a.call(b,d,c,this)&&g.push(d)}return g};if(!Array.prototype.indexOf)Array.prototype.indexOf=function(a,b){var c,d;c=b||0;for(d=this.length;c<d;c+=1)if(this[c]===a)return c;return-1};
function u(a){return Array.prototype.slice.call(a,0)}function ja(a,b){var c=a.slice(b+1||a.length);a.length=b<0?a.length+b:b;a.push.apply(a,c)}"attachEvent"in document&&(u=function(a){var b,c,d=[];b=0;for(c=a.length;b<c;b+=1)d.push(a[b]);return d});function v(a,b){if(a.className)w(a,b)||(a.className+=" "+b);else a.className=b;if(A)a.className=a.className}function sa(a,b){a.className=a.className.replace(RegExp("(^|\\s)"+b+"(\\s|$)"),"$2")}function w(a,b){return!!(a.className&&RegExp("(^|\\s)"+b+"(\\s|$)").test(a.className))}
function B(a,b){b||(b=document);var c=[];if("querySelectorAll"in b)c=u(b.querySelectorAll("."+a));else{var d=RegExp("(^|\\s)"+a+"(\\s|$)");u(b.getElementsByTagName("*")).forEach(function(e){d.test(e.className)&&c.push(e)})}return c}function ta(a,b){b||(b=document);return u(b.getElementsByTagName(a))}
function ua(a,b,c,d){d||(d=document);c=c||"*";if("querySelectorAll"in d)return u(d.querySelectorAll(c+"["+a+(b?'~="'+b+'"':"")+"]"));else{var e=[];c=ta(c,d);var g=b?RegExp("(^|\\s)"+b.replace(/[.*+?\^${}()|\[\]\/\\]/g,"\\$&")+"(\\s|$)"):{test:function(){return f}};a=a==="class"?"className":a;c.forEach(function(h){C(h,a)&&g.test(h.getAttribute(a))&&e.push(h)});return e}}function C(a,b){return"hasAttribute"in a?a.hasAttribute(b):b==="className"?a.className!=="":a.getAttribute(b)!==i}
function va(a){for(;a.firstChild;)a.removeChild(a.firstChild)}function wa(a){if("outerHTML"in a)return a.outerHTML;a=a.cloneNode(f);var b;xa.appendChild(a);b=xa.innerHTML;xa.removeChild(a);return b}function ya(a){document.body.appendChild(xa);xa.innerHTML=a;a=xa.firstChild;va(xa);document.body.removeChild(xa);if(!a||a.nodeType!==1)return i;return a}if("Node"in window&&Node.prototype&&!Node.prototype.contains)Node.prototype.contains=function(a){return!!(this.compareDocumentPosition(a)&16)};
var za=ta("base")[0]||ta("script")[0];function Aa(a){za.parentNode.insertBefore(a,za)}var xa=document.createElement("div");xa.style.display="none";var Ba,Ca,D=window.navigator.userAgent.toLowerCase(),A=!("localStorage"in window&&"querySelectorAll"in document&&"JSON"in window),Da=document.compatMode!=="BackCompat"&&"XMLHttpRequest"in window&&!!(document.addEventListener||document.attachEvent)&&!!(document.documentElement.currentStyle||window.getComputedStyle)&&("querySelectorAll"in document||"attachEvent"in document&&!("addEventListener"in document)),Ea="documentMode"in document&&document.documentMode<=7,Ga=Fa==="android"||/mobile/.test(D),Ha=
window.screen.width<=600,Ia=/webkit/.test(D)?/chrome|safari/.test(D)?/(chrome|safari)/.exec(D)[0]:"webkit":/opera/.test(D)?"opera":/msie/.test(D)?"msie":!/compatible/.test(D)&&/mozilla/.test(D)?"mozilla":"unknown",Fa=(/(android|ipad|iphone|ipod|win|mac|linux)/.exec(window.navigator.platform?window.navigator.platform.toLowerCase():/android/.test(D)?"android":"unknown")||["unknown"])[0],Ja=function(){switch(Ia){case "chrome":case "safari":case "webkit":return"-webkit-";case "mozilla":return"-moz-";
case "msie":return"-ms-";case "opera":return"-o-";default:return""}}(),Ka=function(){switch(Ia){case "chrome":case "safari":case "webkit":return"Webkit";case "mozilla":return"Moz";case "msie":return"ms";case "opera":return"O";default:return""}}();function La(a,b,c){var d=document.documentElement.style;b=b&&Ka?Ka+a.charAt(0).toUpperCase()+a.substr(1):k;return!c&&typeof d[a]!=="undefined"||!!b&&typeof d[b]!=="undefined"}
var Ma="orientation"in window,Na="createTouch"in document||/android/.test(D),Oa=function(){if(window.navigator.plugins&&window.navigator.plugins.length)return!!window.navigator.plugins["Shockwave Flash"];else if("ActiveXObject"in window)try{return!!new window.mc("ShockwaveFlash.ShockwaveFlash.7")}catch(a){}return k}(),Pa=function(){if(A)return k;if("CSSFontFaceRule"in window)return f;if(Ia==="msie")return f;return k}(),Ra="getItems"in document,Sa="getContext"in document.createElement("canvas");
if("createElementNS"in document)var Ta="createSVGRect"in document.createElementNS("http://www.w3.org/2000/svg","svg"),Ua=/SVG/.test(document.createElementNS("http://www.w3.org/2000/svg","animate").toString()),Va=/SVG/.test(document.createElementNS("http://www.w3.org/2000/svg","clipPath").toString());else Ta=Ua=Va=k;var Wa,Xa=document.createElement("div");Xa.innerHTML="<svg/>";Wa=(Xa.firstChild&&Xa.firstChild.namespaceURI)=="http://www.w3.org/2000/svg";
var Ya="canPlayType"in document.createElement("video"),Za="localStorage"in window&&!A,$a="applicationCache"in window,ab=La("transformProperty")||La("transform",f,f),bb,cb=La("perspectiveProperty")||La("perspective",f,f);
if(cb&&"WebkitPerspective"in document.documentElement.style&&Ia!=="safari"){var db=document.createElement("style"),eb=document.createElement("div"),fb="@media (perspective)",gb;fb+=",("+Ja+"perspective)";db.textContent=fb+"{#ts-test {height:3px}}";eb.setAttribute("id","ts-test");Aa(db);Aa(eb);gb=eb.offsetHeight===3;db.parentNode.removeChild(db);eb.parentNode.removeChild(eb);cb=gb}bb=cb;var hb=La("transitionProperty",f);function E(a){return a?"":"no-"}var ib=k;
function jb(){if(!Ba){Ba=[];Ba.push("js",E(Sa)+"canvas",E(Za)+"localstorage",E(Ya)+"video",E($a)+"applicationcache",E(Pa)+"fontface",E(Na)+"touch",E(ab)+"csstransforms",E(bb)+"csstransforms3d",E(hb)+"csstransitions",E(Ta)+"svg",E(Wa)+"inlinesvg",E(Ua)+"smil",E(Va)+"svgclippaths",E(Ra)+"microdata",E(Da)+"treesaver",E(Oa)+"flash",E(Ma)+"orientation",E(A)+"legacy",E(Ga)+"mobile",E(Ha)+"smallscreen",E(F.cb())+"cached",E(k)+"nativeapp","browser-"+Ia,"os-"+Fa)}Ca=[E(!F.va())+"offline"];Ma&&Ca.push("orientation-"+
(window.orientation?"horizontal":"vertical"));var a=document.documentElement.className;if(!ib){ib=f;a=a?a.replace(/no-js|no-treesaver/g,""):"";a+=" "+Ba.join(" ")}a=a.replace(kb,"");a+=" "+Ca.join(" ");document.documentElement.className=a.split(/\s+/).join(" ")}var lb=["offline","orientation-vertical","orientation-horizontal"],kb=function(){var a=lb.map(function(b){return"((no-)?"+b+")"});return RegExp(a.join("|"))}();
function mb(a,b){if(!a.length)return f;return a.every(function(c){var d=c.substr(0,3)==="no-";c=d?c.substr(3):c;var e=Ba.concat(b?Ca:[]);if(d)return e.indexOf(c)===-1;else{if(e.indexOf(c)!==-1)return f;if(!b&&lb.indexOf(c)!==-1)return f;return k}})};function nb(a,b){"insertRule"in ob?ob.insertRule(a+"{"+b+"}",0):ob.addRule(a,b)}var ob=document.createElement("style");ob.setAttribute("type","text/css");
if(ta("head").length){ta("head")[0].appendChild(ob);ob=document.styleSheets[document.styleSheets.length-1];nb(".offscreen","position:absolute;top:-200%;right:-200%;visibility:hidden;");nb(".grid","top:50%");if(hb){nb(".grid, .scroll-container","transition:transform cubic-bezier(0,0,0.25,1) 0.2s");Ja&&nb(".grid, .scroll-container",Ja+"transition:"+Ja+"transform cubic-bezier(0,0,0.25,1) 0.2s");if(bb){nb(".grid, .scroll-container","backface-visibility:hidden");Ja&&nb(".grid, .scroll-container",Ja+"backface-visibility:hidden")}}};function pb(a){return document.defaultView.getComputedStyle(a,i)}!(document.defaultView&&document.defaultView.getComputedStyle)&&(pb=function(a){return a.currentStyle});var qb=/^-?\d+(?:px)?$/i,tb=/^-?\d/;function ub(a,b){if(!a)return k;var c=a.k||a.k===0?a.k:a.b;return b.c>=(a.w||a.w===0?a.w:a.c)&&b.b>=c&&b.c<=a.Ha&&b.b<=a.T}function H(a,b){if(b&&qb.test(b))return parseFloat(b)||0;return i}function I(a){return a&&a.offsetHeight||0}function J(a){return a&&a.offsetWidth||0}function vb(a){return a&&a.offsetTop||0}
if(!(document.defaultView&&document.defaultView.getComputedStyle)){if(A){vb=function(a){if(a){a.style.zoom=1;return a.offsetTop}return 0};I=function(a){if(a){a.style.zoom=1;return a.offsetHeight}return 0};J=function(a){if(a){a.style.zoom=1;return a.offsetWidth}return 0}}H=function(a,b){var c,d,e;if(b&&qb.test(b))return parseFloat(b);else if(b&&tb.test(b)){c=a.style.left;d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b||0;e=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=
d;return e}return i}}function K(a,b,c){a.style[b]=c+"px";return c}if(ab)var wb=function(a,b){if("transformProperty"in a.style)a.style.transformProperty=b;else a.style[Ka+"Transform"]=b},xb=bb?function(a,b,c){wb(a,"translate3d("+b+"px,"+c+"px,0)")}:function(a,b,c){wb(a,"translate("+b+"px,"+c+"px)")},yb=function(a,b){xb(a,b,0)};else{xb=function(a,b,c){K(a,"left",b);K(a,"top",c)};yb=function(a,b){K(a,"left",b)}}function zb(a,b){return Math.ceil(a)+b-a%b}
function L(a){if(a){var b=pb(a);a.getAttribute("style");var c;this.display=b.display;this.position=b.position;if(A)a.style.zoom=1;this.marginTop=H(a,b.marginTop)||0;this.marginBottom=H(a,b.marginBottom)||0;this.marginLeft=H(a,b.marginLeft)||0;this.marginRight=H(a,b.marginRight)||0;this.marginHeight=this.marginTop+this.marginBottom;this.marginWidth=this.marginLeft+this.marginRight;this.borderTop=H(a,b.borderTopWidth);this.borderBottom=H(a,b.borderBottomWidth);this.borderLeft=H(a,b.borderLeftWidth);
this.borderRight=H(a,b.borderRightWidth);this.paddingTop=H(a,b.paddingTop);this.paddingBottom=H(a,b.paddingBottom);this.paddingLeft=H(a,b.paddingLeft);this.paddingRight=H(a,b.paddingRight);this.D=this.borderTop+this.paddingTop;this.ga=this.borderBottom+this.paddingBottom;this.X=this.D+this.ga;this.Ob=this.borderLeft+this.paddingLeft;this.Pb=this.borderRight+this.paddingRight;this.Sa=this.Ob+this.Pb;this.oa=J(a);this.m=I(a);this.c=this.oa-this.Sa;this.b=this.m-this.X;this.w=H(a,b.minWidth)||0;this.k=
H(a,b.minHeight)||0;c=H(a,b.maxWidth);this.Ha=!c||c===-1?Infinity:c;c=H(a,b.maxHeight);this.T=!c||c===-1?Infinity:c;this.lineHeight=H(a,b.lineHeight)||i}}L.prototype.F=function(){var a=new L,b;for(b in this)a[b]!==this[b]&&(a[b]=this[b]);return a};function M(a,b,c){var d=document.createEvent("UIEvents"),e;d.initEvent(b,k,f);if(c)for(e in c)d[e]=c[e];return a.dispatchEvent(d)}function N(a,b,c){a.addEventListener(b,c,k)}function Q(a,b,c){a.removeEventListener(b,c,k)}
if(!("addEventListener"in document)){var Ab=["abort","activate","afterprint","afterupdate","beforeactivate","beforecopy","beforecut","beforedeactivate","beforeeditfocus","beforepaste","beforeprint","beforeunload","beforeupdate","blur","bounce","cellchange","change","click","contextmenu","controlselect","copy","cut","dataavailable","datasetchanged","datasetcomplete","dblclick","deactivate","drag","dragend","dragenter","dragleave","dragover","dragstart","drop","error","error","errorupdate","filterchange",
"finish","focus","focusin","focusout","hashchange","help","keydown","keypress","keyup","layoutcomplete","load","losecapture","message","mousedown","mouseenter","mouseleave","mousemove","mouseout","mouseover","mouseup","mousewheel","move","moveend","movestart","offline","online","page","paste","progress","propertychange","readystatechange","readystatechange","reset","resize","resizeend","resizestart","rowenter","rowexit","rowsdelete","rowsinserted","scroll","select","selectionchange","selectstart",
"start","stop","storage","storagecommit","submit","timeout","unload"],Bb=function(){this.returnValue=k},Cb=function(){this.cancelBubble=f};M=function(a,b,c){var d=document.createEventObject(),e;d.type=b;if(c)for(e in c)d[e]=c[e];if(!d.preventDefault)d.preventDefault=Bb;if(!d.stopPropagation)d.stopPropagation=Cb;try{return a.fireEvent("on"+b,d)}catch(g){}a.p&&a.p[b]&&a.p[b].gb(d);return k};var Db=function(a,b){return function(c){c=c||window.event;c.target=c.target||c.srcElement;c.preventDefault=Bb;
c.stopPropagation=Cb;a.p[b].sa.forEach(function(d){try{"handleEvent"in d?d.handleEvent(c):d.call(a,c)}catch(e){}})}};N=function(a,b,c){if(!a.p)a.p={};if(!a.p[b]){a.p[b]={sa:[],gb:Db(a,b)};Ab.indexOf(b)!==-1&&a.attachEvent("on"+b,a.p[b].gb)}a.p[b].sa.push(c)};Q=function(a,b,c){if(a.p&&a.p[b]){c=a.p[b].sa.indexOf(c);c!==-1&&ja(a.p[b].sa,c);if(!a.p[b].sa.length){Ab.indexOf(b)!==-1&&a.detachEvent("on"+b,a.p[b].gb);a.p[b]=i}}}}ca("treesaver.addListener",N,void 0);ca("treesaver.removeListener",Q,void 0);var Eb={};function Fb(a,b,c){this.fa=a;this.t=b;this.g=c}var Gb=new Fb(Infinity,Infinity,Infinity);function Hb(a,b){if(a.fa!==b.fa)return b.fa-a.fa;else if(a.g!==b.g)return a.g-b.g;return b.t-a.t}Fb.prototype.F=function(){return new this.constructor(this.fa,this.t,this.g)};function Ib(){this.g=this.f=this.index=0;this.I=k;this.s=[];this.ka=[];this.xa=0}Ib.prototype.F=function(){var a=new this.constructor;a.index=this.index;a.f=this.f;a.g=this.g;a.I=this.I;a.s=this.s.slice(0);a.ka=this.ka.slice(0);a.xa=this.xa;return a};
function Jb(a,b){if(a.g)return k;var c,d,e;c=a.index;for(d=b.i.length;c<d;c+=1){e=b.i[c];if(!e.ua)return k;if(!Kb(a,c)&&!e.t.da)return k}if(!a.s.length&&a.f===b.l.length)return f;for(c=a.s.slice(0);c.length;){e=b.l[c.pop()];if(!e.da)return k}c=a.f;for(d=b.l.length;c<d;c+=1){e=b.l[c];if(!e.da)return k}return f}function Lb(a,b){var c;if(b<a.f)if((c=a.s.indexOf(b))!==-1)ja(a.s,c);else(c=a.ka.indexOf(b))!==-1&&ja(a.ka,c);else{if(b>a.f)for(;a.f<b;a.f+=1)a.s.push(a.f);a.f=b+1}}
function Mb(a,b){if(a.s.indexOf(b)===-1){Lb(a,b);a.s.push(b)}}function Kb(a,b){if(a.f<=b)return k;if(a.s.indexOf(b)!==-1)return k;if(a.ka.indexOf(b)!==-1)return k;return f};function Nb(a,b,c,d){this.j=a;this.w=parseInt(b||0,10);this.k=parseInt(c||0,10);this.C=d}Nb.prototype.ca=function(){if(!this.C)return f;return mb(this.C,f)};function Ob(a,b,c){c&&v(b,c);b.innerHTML=a.j;ua("data-src",i,"img",b).forEach(function(d){d.setAttribute("src",d.getAttribute("data-src"))})};if(!String.prototype.trim)String.prototype.trim=function(){return this.replace(/^\s\s*/,"").replace(/\s\s*$/,"")};var Pb={};function Qb(a){var b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push(c);return b}Object.F=function(a){function b(){}b.prototype=a;return new b};function Rb(a,b){Sb(a,b)}
function Sb(a,b){var c=[],d=[],e,g,h,o;c=ua("data-bind",i,i,b);e=0;for(h=c.length;e<h;e+=1){o=k;for(g=0;g<h;g+=1)if(c[e]!==c[g]&&c[g].contains(c[e])){o=f;break}o||d.push(c[e])}C(b,"data-bind")&&d.push(b);d.forEach(function(l){l.getAttribute("data-bind").split(/\s+/).forEach(function(j){var s=j.indexOf(":"),r=i,n=i,p=i,x=[],y="";if(s!==-1){r=j.substring(0,s);n=j.substring(s+1)}else r=j;if(a[r]){p=a[r];if(Object.prototype.toString.apply(p)==="[object Array]"){x=u(l.childNodes);p.forEach(function(t){x.forEach(function(z){z=
z.cloneNode(f);z.nodeType===1&&Sb(t,z);l.appendChild(z)})});x.forEach(function(t){l.removeChild(t)})}else if(Object.prototype.toString.apply(p)==="[object Object]"){x=u(l.childNodes);x.forEach(function(t){t.nodeType===1&&Sb(p,t)})}else{if(n!==i)if((n==="href"||n==="src")&&C(l,"data-"+n)){if(!(C(l,n)&&/{{[^}]+}}/.test(y=l.getAttribute(n))))y=l.getAttribute("data-"+n)}else y=n==="class"?l.className:l.getAttribute(n);else y=l.innerHTML;p||(p="");p=p.toString();y=y&&/{{[^}]+}}/.test(y)?y.replace(/{{([^}]+)}}/g,
function(t,z){z=z.trim();return z===r?n!==i&&(n==="href"||n==="src")?encodeURIComponent(p):n?p:Tb(p):"{{"+z+"}}"}):Tb(p);if(n)if(n==="class")l.className=y;else l.setAttribute(n,y);else l.innerHTML=y}}})})}function Wb(a,b){return a.getAttribute("data-bind").split(/\s+/).some(function(c){var d=c.indexOf(":");return d!==-1?c.substring(0,d)===b:c===b})}function Xb(a,b){return ua("data-bind",i,i,b).filter(function(c){return Wb(c,a)})}
function Tb(a){return a.replace(/&(?!\w+;)|[<>]/g,function(b){switch(b){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";default:return b}})};function Yb(a,b,c){this.nc=c.index;this.f=c.f;c.f+=1;this.la=i;this.q={};this.da=!w(a,"required");this.Jb=w(a,"zoomable");this.jc=[];u(a.childNodes).forEach(function(d){if(d.nodeType!==1)d.data&&d.data.trim();else{var e=d.getAttribute("data-sizes"),g=parseInt(d.getAttribute(C(d,"width")?"width":"data-minwidth"),10),h=parseInt(d.getAttribute(C(d,"height")?"height":"data-minheight"),10),o=C(d,"data-requires")?d.getAttribute("data-requires").split(" "):i;if(!(o&&!mb(o))){d.removeAttribute("hidden");
sa(d,"hidden");d=wa(d);e=e?e.split(" "):["fallback"];Zb(this,e,d,g,h,o)}}},this);if(this.q.fallback){$b(this,this.q.fallback[0].j,a,b,c);delete this.q.fallback}delete this.jc}
function $b(a,b,c,d,e){var g=c.parentNode,h=document.createElement("div");h.innerHTML=b;b=h.childNodes.length===1?h.firstChild:h;g.insertBefore(b,c);if(a.Jb){v(b,"zoomable");b.setAttribute("data-figureindex",a.f);Na&&b.setAttribute("onclick","void(0)")}ac(b,d);a.la=new bc(b,d,e,f);a.la.t=a;a.la.i&&a.la.i.forEach(function(o){o.t=this;o.Ib=f},a);g.removeChild(b)}
function cc(a,b){var c=-Infinity,d=-Infinity,e,g;for(g in a.q)a.q[g].forEach(function(h){if(h.ca()&&!(h.w&&h.w>b.c||h.k&&h.k>b.b))if((!h.w||h.w>=c)&&(!h.k||h.k>=d)){c=h.w;d=h.k;e={name:g,Ea:h}}});return e}function Zb(a,b,c,d,e,g){var h=new Nb(c,d,e,g);b.forEach(function(o){if(this.q[o])this.q[o].push(h);else this.q[o]=[h]},a)}function dc(a){var b=a.nodeName.toLowerCase();return a.nodeType===1&&b==="figure"};function bc(a,b,c,d){var e=ec(a),g,h="";if(a.nodeType!==1)this.ta=f;else if(I(a)){this.index=c.index;c.index+=1;this.aa=!e&&fc(a);this.$=this.Ib=this.ua=k;this.t=i;this.i=[];this.l=[];g=k;if(this.aa&&!w(a,"keeptogether")){gc(this,a,b,c,d);g=!!this.l.length;this.aa=!!this.i.length}this.Ta=this.Ta||!e;this.Wb=w(a,"keepwithnext");this.Qb=w(a,"columnbreak");this.ma=this.ma||!this.Ta||w(a,"keeptogether");this.d=new L(a);if(!this.d.lineHeight)this.d.lineHeight=b;if(!this.ma)this.ma=this.d.X+this.d.lineHeight===
this.d.m;this.ra=this.ma?this.d.m:!this.aa?this.d.D+this.d.lineHeight:!this.$?this.d.D+this.i[0].ra+(this.d.D?this.i[0].d.marginTop:0):this.d.D+this.i[0].ra;this.j=wa(a);this.zb=this.aa?this.j.substr(0,this.j.indexOf(">")+1):i;this.Ua=this.aa?this.j.slice(this.j.lastIndexOf("<")):i;if(g){this.j=this.zb;this.i.forEach(function(o){this.j+=o.j},this);this.j+=this.Ua}if(this.aa){a=a.cloneNode(f);this.d.marginTop&&K(a,"marginTop",0);this.d.borderTop&&K(a,"borderTopWidth",0);this.d.paddingTop&&K(a,"paddingTop",
0);h=wa(a)}this.ac=this.aa?h.substr(0,h.indexOf(">")+1):i}else this.ta=f}function hc(a){return a.nextSibling?a.nextSibling:a.parent?hc(a.parent):i}
function gc(a,b,c,d,e){var g,h=a instanceof bc,o=b.nodeName.toLowerCase()==="ol"&&"start"in b,l=o?b.start:i;l===-1&&(l=1);u(b.childNodes).forEach(function(j){if(o&&j.nodeName.toLowerCase()==="li"){if(j.value&&j.value!==-1)l=j.value;j.setAttribute("value",l);l+=1}if(dc(j)){if(e)return;j=new Yb(j,c,d);a.l.push(j);if(j=j.la){j.ua=f;if(h)a.$=f}}else{j=new bc(j,c,d,!!e);if(h&&!a.$)a.$=j.$}if(j&&!j.ta){a.i=a.i.concat(j,j.i||[]);if(j.l.length){a.l=a.l.concat(j.l);delete j.l}j.parent=h?a:i;if(g)g.nextSibling=
j;g=j}})}function ic(a){a=a.parent;for(var b=[];a;){b.unshift(a.ac);a=a.parent}return b.join("")}function jc(a){a=a.parent;for(var b=[];a;){b.push(a.Ua);a=a.parent}return b.join("")}
function fc(a){if(kc(a))return k;if(lc(a))return f;var b,c,d,e=k;b=0;for(c=a.childNodes.length;b<c;b+=1){d=a.childNodes[b];if(d.nodeType===3&&/[^\s]/.test(d.data))return k;else if(d.nodeType===1){if(kc(d)||lc(d))return f;e=f;d=pb(d);if(/inline/.test(d.display))return k;else if(/block/.test(d.display))return f}}return e}var nc=["img","video","object","embed","iframe","audio","canvas","svg","table"];function ec(a){var b=a.nodeName.toLowerCase();return a.nodeType===1&&nc.indexOf(b)!==-1}
var oc=["p","h1","h2","h3","h4","h5","h6"];function kc(a){var b=a.nodeName.toLowerCase();return a.nodeType===1&&oc.indexOf(b)!==-1}var pc=["div","article","ul","ol","figure","aside"];function lc(a){var b=a.nodeName.toLowerCase();return a.nodeType===1&&pc.indexOf(b)!==-1}
function ac(a,b){if(a.nodeType===1){var c,d;a.removeAttribute("id");if(!dc(a)){if(fc(a)&&!w(a,"keeptogether"))for(c=a.childNodes.length-1;c>=0;c-=1){d=a.childNodes[c];d.nodeType!==1?a.removeChild(d):ac(d,b)}if(!window.TS_NO_AUTOMETRICS){c=new L(a);c.marginTop%b&&K(a,"marginTop",zb(c.marginTop,b));c.marginBottom%b&&K(a,"marginBottom",zb(c.marginBottom,b));if(ec(a)||w(a,"keeptogether"))c.m%b&&K(a,"paddingBottom",c.paddingBottom+b-c.m%b);else{if(c.lineHeight)c.lineHeight%b&&K(a,"lineHeight",zb(c.lineHeight,
b));else{c.lineHeight=b;K(a,"lineHeight",b)}c.D%b&&K(a,"paddingTop",zb(c.D,b)-c.borderTop);if(c.ga%b)c.paddingBottom=K(a,"paddingBottom",zb(c.ga,b)-c.borderBottom);c.m=I(a);if(c.m%b){c.paddingBottom+=b-c.m%b;K(a,"paddingBottom",c.paddingBottom)}}}}}};function qc(a){this.lineHeight=H(a,pb(a).lineHeight)||1;this.Z=a.offsetWidth;ta("figure",a).forEach(function(b){b.style.display="none"});ac(a,this.lineHeight);this.l=[];this.i=[];gc(this,a,this.lineHeight,{index:0,f:0});this.H={};rc(a).forEach(function(b){var c=sc(b);Qb(c).forEach(function(d){this.H[d]||(this.H[d]=c[d])},this)},this)};function tc(a,b){var c=new L(a);this.u=!w(a,"fixed");(this.k=c.k)&&K(a,"minHeight",0);this.b=c.m;this.Ca=Math.max(0,b-this.b)}tc.prototype.za=function(a){if(!this.u)return this;this.b=Math.max(0,a-this.Ca);return this};function uc(a,b){var c=new L(a);this.u=!w(a,"fixed");(this.k=c.k)&&K(a,"minHeight",0);this.b=c.m;this.Ca=Math.max(0,b-this.b);this.q=(c=a.getAttribute("data-sizes"))?c.split(" "):[]}uc.prototype.za=function(a){if(!this.u)return this;this.b=Math.max(0,a-this.Ca);return this};function vc(a){document.body.appendChild(a);this.C=C(a,"data-requires")?a.getAttribute("data-requires").split(" "):i;var b;b=a.className?a.className.toLowerCase().split(/\s+/):[];this.tb=b;this.u=!w(a,"fixed");wc(this);this.Aa=this.size=new L(a);if(this.u)this.size.w=Math.max(this.size.w||0,this.size.c);else{this.size.k=this.size.b;this.size.w=this.size.c}this.lineHeight=this.size.lineHeight||1;this.Z=this.ba=this.W=0;this.error=k;this.cols=[];B("column",a).forEach(function(c){var d=new tc(c,this.size.b);
this.cols.push(d);this.W+=d.b;this.ba=Math.max(this.ba,d.b);if(this.Z){if(this.Z!==c.offsetWidth)this.error=f}else this.Z=c.offsetWidth},this);this.G=[];B("container",a).forEach(function(c){this.G.push(new uc(c,this.size.b))},this);this.j=wa(a);document.body.removeChild(a)}var xc={onlypage:f,odd:f,even:f,sizetocontainer:f},yc=/^(no-)?page-(\d+)$/;
function wc(a){var b=k,c,d;a.K={};a.Ja={};a.Ab={};a.tb.forEach(function(e){if(e in xc)this.K[e]=f;else if(c=yc.exec(e)){d=parseInt(c[2],10);if(!isNaN(d))if(e.substr(0,3)==="no-")this.Ab[d]=f;else{b=f;this.Ja[d]=f}}},a);if(!b)a.Ja=i}
vc.prototype.za=function(a){if(!this.u)return this;var b=Math.min(this.size.T,Math.max(a-(this.size.marginHeight+this.size.X),this.size.k));b-=(b-this.size.k||0)%this.lineHeight;this.W=this.ba=0;this.cols.forEach(function(c){this.W+=c.za(b).b;this.ba=Math.max(this.ba,c.b)},this);this.G.forEach(function(c){c.za(b)},this);this.Aa=this.size.F();this.Aa.b=b;this.Aa.m=b+this.size.X;this.Aa.T=this.K.sizetocontainer?this.size.T:Math.min(this.size.T,b+this.lineHeight*3);return this};
function zc(a,b){return b.size.c+20*b.G.length-(a.size.c+20*a.G.length)}
function Ac(a,b,c){var d=i,e=-Infinity,g,h,o=a.i.length,l,j,s,r,n,p,x,y,t,z,G,O,Z;s=0;r=b.length;for(;s<r;s+=1){n=b[s];O=0;Z=k;g=c.F();x=g.g;y=n.W-x;x&&n.W&&(Z=f);p=0;h=g.xa+1;p+=n.cols.length*50;n.lineHeight!==a.lineHeight&&(p-=2E3);n.Z&&n.Z!==a.Z&&(p-=Infinity);n.K.onlypage&&(p+=g.xa?-Infinity:4E3);if(n.Ja)if(n.Ja[h])p+=3E3;else p-=Infinity;n.Ab[h]&&(p-=Infinity);p+=h%2?n.K.odd?2E3:n.K.even?-Infinity:0:n.K.even?2E3:n.K.odd?-Infinity:0;h=n;l=a;j=g;t=void 0;z=void 0;G=void 0;var q=void 0,$=void 0,
P=void 0,aa=void 0,Ub=void 0,V=void 0,rb=void 0,cd=void 0,Vb=[];t=0;z=h.G.length;for(;t<z;t+=1){G=h.G[t];Vb[t]=i;P=j.f;rb=j.s.slice(0);c:for(;rb.length||P<l.l.length;){aa=(cd=!!rb.length)?rb.shift():P;Ub=l.l[aa];q=G.q.length-1;d:for(;q>=0;q-=1){$=G.q[q];e:{V=Ub;var sb=$,Qa=void 0,dd=void 0;if(V.q[sb]){Qa=0;for(dd=V.q[sb].length;Qa<dd;Qa+=1)if(V.q[sb][Qa].ca()){V=V.q[sb][Qa];break e}}V=i}if(V){if(G.u&&V.k&&V.k>G.b)continue d;Vb[t]={f:aa,Ea:V,size:$,u:G.u};Lb(j,aa);break c}}if(!Ub.da)break;cd||(P+=
1)}}h=Vb;j=0;t=h.length;for(;j<t;j+=1){z=n.G[j];if(G=h[j]){l=a.l[G.f];p+=2E3+G.Ea.k*5;l.da||(p+=4E3);z.u||(p+=5E3);O+=1}else z.u||(p-=5E3)}b:for(;n.W&&g.index<o&&x<=n.W;){l=a.i[g.index];j=l.d.m+l.d.marginTop;if(l.ma&&(j>n.ba||j>y))break b;if(j>y){if(l.ma)break b;if(l.children){g.index+=1;continue b}x+=j}x+=j;p+=j;y-=j;Z=f;g.index=l.nextSibling?l.nextSibling.index:g.index+1}if(Z){if(y>0){g=y/n.W;g-=O*0.2;if(g>0.5){p-=y;p-=g*g*2E3}}}else if(O){if((l=a.i[g.index])&&l.t&&!l.t.da&&(g.g||l.Ib))p=-Infinity}else p=
-Infinity;if(p>e){e=p;d={N:n,G:h}}}return d};function Bc(a,b,c){var d=Ac(a,b,c);b=document.createElement("div");var e=c.F(),g=k;if(!d||!d.N){c.I=Jb(c,a)||c.f===a.l.length;if(c.I)this.ta=f;else this.error=f}else{this.size=d.N.Aa.F();this.rb=new Fb(c.index,c.f,c.g);v(b,"offscreen");document.body.appendChild(b);b.innerHTML=d.N.j;this.a=b.firstChild;K(this.a,"width",this.size.c);K(this.a,"height",this.size.b);Qb(a.H||{}).forEach(function(h){Xb(h,this.a).forEach(function(o){var l={};l[h]=a.H[h];Sb(l,o)})},this);B("container",this.a).forEach(function(h,
o){var l=d.G[o],j,s,r;if(l){s=l.f;j=a.l[s];var n=a.lineHeight,p,x,y;r=f;p=l.size;x=l.Ea;y=I(h);Ob(x,h,p);if(l.u){if(w(h,"bottom")){r=k;h.style.top="auto"}else h.style.bottom="auto";l=I(h);if(l>y){sa(h,p);va(h);r=k}else{n&&l%n&&(l=zb(l,n));for(n=h;n=n.nextSibling;)if(n.nodeType===1&&!w(n,"fixed")&&(w(n,"column")||w(n,"container")||w(n,"group"))){v(n,"flexed");if(I(n)<=l)K(n,"height",0);else r?K(n,"top",vb(n)+l):K(n,"bottom",I(n.offsetParent)-(vb(n)+I(n))+l)}r=f}}else r=f;if(r){Lb(c,s);g=f;if(j.Jb){v(h,
"zoomable");h.setAttribute("data-figureindex",s);Na&&h.setAttribute("onclick","void(0)")}if(o===0&&d.N.K.sizetocontainer){this.size.b=I(h)+d.N.G[0].Ca;this.size.m=this.size.b+this.size.X;K(this.a,"height",this.size.b)}}else{if(!j.da&&j.la)Mb(c,j.f);else if(!w(h,"flexed")){Lb(c,s);c.ka.push(s)}h.parentNode.removeChild(h)}}else h.parentNode.removeChild(h)},this);B("column",this.a).forEach(function(h,o){var l=d.N.ba,j=d.N.cols[o].k,s=I(h),r=0,n,p,x=f,y=0,t=0,z=0,G=0,O=[],Z=a.i.length,q=a.i[c.index],
$,P;t=[];var aa;t=k;l=l/s>1.5;if(q){s%a.lineHeight&&(s-=s%a.lineHeight);if(!(!s||s<j)){q.parent&&O.push(ic(q));y=c.g?q.d.m-c.g:0;a:for(;c.index<Z&&r<s;){q=a.i[c.index];P=($=q.nextSibling)||hc(q);if(q.ua&&Kb(c,q.t.f)&&!(x&&c.g)){c.index=P?P.index:Z;continue a}j=q.parent;n=s-r;if(x&&!z){z=-y;t=c.overflow?q.d.lineHeight:q.ra}else{z=Math.max(z,q.d.marginTop);t=z+q.ra}G=Math.max(q.d.marginBottom,$?$.d.marginTop:0);aa=q.d.m+z;t=n<t;if(!t&&q.Wb&&$&&!(c.g||x&&!l))t=n>=aa&&n<aa+G+$.ra;t&&(t=!x||l);t&&(t=!q.$);
q.Qb&&!x&&(t=f);if(t){if(j){for(;j&&j.index===q.index-1;){O.pop();c.index=j.index;j.ua&&Mb(c,j.t.f);q=j;j=q.parent}j&&O.push(jc(q))}break a}q.ua&&Lb(c,q.t.f);if(q.$||q.i.length&&n<aa){if(q.d.D){r+=x?0:z;z=0;r+=q.d.D}O.push(q.zb);c.index+=1;continue a}r+=aa;O.push(q.j);x=k;p=p||q;c.g=0;if(s>r+G){c.index=P?P.index:Z;if(!$&&j){t=[];do{t.push(j.Ua);if(j.d.ga){r+=G+j.d.ga;G=j.d.marginBottom}else G=Math.max(G,j.d.marginBottom)}while(!j.nextSibling&&(j=j.parent));if(s>r+G)O.push(t.join(""));else{j&&O.push(jc(q));
r=s;break a}}z=G;continue a}j&&O.push(jc(q));if(q.Ta){if(r<=s){c.index=P?P.index:Z;r=s}}else{r=s;c.index=P?P.index:Z}break a}x=q;if(s>=r||!x)c.g=0;else{c.g=r-s;r=c.g-x.d.ga;if(r<=0){c.g=0;c.index=x.index+1}else if(r=(x.d.b-r)%x.d.lineHeight){s-=r;c.g+=r}}K(h,"height",s);h.innerHTML=O.join("");if(p&&h.firstChild){h.firstChild.style.marginTop=-y+"px";if(p.parent&&!y){for(j=p.parent;j;){j.d.D&&(p=j);j=j.parent}if(j!==p){j=p.parent;for(q=h.firstChild;j;){q=q.firstChild;j=j.parent;if(q)q.style.marginTop=
0}}}else if(p.i.length&&!y)for(q=h.firstChild;p;)if(p.i.length&&q.firstChild){p=p.i[0];q=q.firstChild;q.style.marginTop=0}else p=i}else va(h)}}});if(c&&c.index===e.index&&c.f===e.f&&c.g===e.g&&c.s.length===e.s.length)this.error=f;else if(!g&&d.N.K.sizetocontainer)this.ta=f;else{K(this.a,"marginTop",-this.size.m/2);this.j=b.innerHTML;this.end=new Fb(c.index,c.f,c.g);this.o=k;c.xa+=1;c.I=d.N.K.onlypage||Jb(c,a)}b.removeChild(this.a);this.a=i;document.body.removeChild(b);b=i}}
Bc.prototype.M=function(){if(this.o)return this.a;this.a=ya(this.j);this.o=f;return this.a};Bc.prototype.A=function(){this.o=k;this.a=i};Bc.prototype.F=function(){var a=Pb.F(this);a.a=this.a&&this.a.cloneNode(f)||i;a.o=this.o;return a};var F={};F.Kb=1E4;F.ja={Mb:"treesaver.online",Lb:"treesaver.offline"};F.Hb=["offline","online"];F.Gb=["uncached","idle","checking","downloading","updateready","obsolete"];F.Ga=k;F.load=function(){if(!F.Ga){F.Ga=f;F.Hb.forEach(function(a){N(document,a,F)});$a&&F.eb&&F.Gb.forEach(function(a){N(window.applicationCache,a,F)})}};F.kc=function(){if(F.Ga){F.Ga=k;F.Hb.forEach(function(a){Q(window,a,F)});$a&&F.eb&&F.Gb.forEach(function(a){Q(window.applicationCache,a,F)})}};
F.va=function(){if("onLine"in window.navigator)return window.navigator.onLine;return f};F.eb=$a&&!!window.applicationCache.status;F.cb=function(){return F.eb};F.handleEvent=function(a){switch(a.type){case "online":jb();M(window,F.ja.Mb);break;case "offline":jb();M(window,F.ja.Lb);break;case "updateready":window.applicationCache.swapCache()}};
F.lc=function(a){var b,c;if(A){c=document.createElement("div");c.style.display="none";document.body.appendChild(c);c.innerHTML='<a href="'+a+'"></a>';b=c.firstChild}else{b=document.createElement("a");b.href=a}a=b.pathname;if(A){document.body.removeChild(c);c.removeChild(b)}a.charAt(0)!=="/"&&(a="/"+a);return a};F.ic=function(a){var b=a.indexOf("#");return b===-1?a:a.substr(0,b)};F.cc=/^https?:\/\//i;
F.Qa=function(a){if(a&&a.charAt(0)==="/"||F.cc.test(a))return a;var b=document.createElement("a"),c;if(A){c=document.createElement("div");document.body.appendChild(c);c.appendChild(b)}b.href=a;a=b.href;if(A){document.body.removeChild(c);c.removeChild(b)}return a};F.get=function(a,b,c){var d={L:new XMLHttpRequest,url:a,sb:b};ma(function(){F.ec(d)},c||F.Kb,[],F.yb(d));d.L.onreadystatechange=F.Rb(d);try{d.L.open("GET",d.url,f);d.L.send(i)}catch(e){F.lb(d)}};F.yb=function(a){return"fetch:"+a.url};
F.Rb=function(a){return function(){if(a.L.readyState===4)if(a.L.status===0||a.L.status===200||a.L.status===304){a.sb(a.L.responseText,a.url);F.ub(a)}else F.lb(a)}};F.ub=function(a){ra(F.yb(a));a.L.onreadystatechange=i};F.lb=function(a){a.sb(i,a.url);F.ub(a)};F.ec=function(a){a.L.abort();F.lb(a)};function Cc(a,b,c,d){this.content=this.pa=i;this.url=a;this.path=F.lc(a);this.title=b;this.Y=i;this.n=0;this.h=[];this.error=this.Zb=this.fb=this.loaded=this.J=this.ya=k;this.ia=this.na=i;this.Za=[];this.$a=c;d&&Dc(this,d)}var Ec=/<title>\s*(.+?)\s*<\/title>/i;
function Dc(a,b){a.loaded=f;var c=document.createElement("div"),d=document.createElement("div"),e;e=(e=Ec.exec(b))&&e[1]?e[1]:i;if(e)a.title=e;c.style.display="none";v(c,"offscreen grid");v(d,"column");document.body.appendChild(c);c.innerHTML=b;if(e=document.getElementById("ts_content")||ta("article",c)[0]){e.removeAttribute("id");va(c);a.pa=e.getAttribute("data-theme")||e.getAttribute("data-grids")||i;if(a.pa){v(c,a.pa);v(d,a.pa);Fc(a,a.$a)}for(;e.firstChild;)d.appendChild(e.firstChild);c.appendChild(d);
d.style.display="block";c.style.display="block";a.content=new qc(d);document.body.removeChild(c);c.removeChild(d);va(d);Gc(a)}else{document.body.removeChild(c);a.error=f}}function Fc(a,b){a.$a=a.pa?b.filter(function(c){return c.tb.indexOf(this.pa)!==-1},a):b.slice(0)}function Hc(a,b){a.Za=a.$a.filter(function(c){var d;d=c.C?mb(c.C,f):f;return d&&ub(c.size,{c:b.c-c.size.Sa,b:b.b-c.size.X-c.size.marginHeight})}).map(function(c){return c.za(b.b)});a.Za.sort(zc)}
function Ic(a,b){if(!a.na||a.na.c!==b.c||a.na.b!==b.b){a.na=b;a.ya=ub(a.ia,b)}return!a.ya}function Gc(a){ra("paginate");a.h=[];a.n=0;a.na&&Hc(a,a.na);a.Y=new Ib;a.ia=i;a.ya=f;a.J=k}
Cc.prototype.bc=function(a,b,c){ra("paginate");var d;for(b=b||0;!this.Y.I;){d=new Bc(this.content,this.Za,this.Y);if(d.ta){if(this.Y.I)break}else{if(d.error){if(this.Y.I)break;this.error=f;M(document,"treesaver.paginationerror",{Q:this});this.Y.I=f;break}this.h.push(d);this.n+=1;this.error=k;var e=this.ia,g=d.size;e=e||{};g=g||{};var h=g.X||(g.m?g.m-g.b:0),o=g.Sa||(g.oa?g.oa-g.c:0);this.ia={c:Math.max(e.c||0,g.c+o||0),b:Math.max(e.b||0,g.b+h||0),Ha:Math.min(e.Ha||Infinity,g.Ha+o||Infinity),T:Math.min(e.T||
Infinity,g.T+h||Infinity)};if(!(b&&this.n<=b||c&&(c===Gb||!(Hb(c,d.end)>=0)))&&!this.Y.I){if(a){M(document,"treesaver.paginationprogress",{Q:this});Jc(this,u(arguments))}return}}}this.J=f;M(document,"treesaver.paginationprogress",{Q:this,oc:f})};function Jc(a,b){ma(Cc.prototype.bc,200,b,"paginate",a)}
function Kc(a,b,c){a.ya||Gc(a);var d=[],e=b>=0?b+c-1:Infinity;!a.J&&e>a.h.length-1&&Jc(a,[f,e]);if(a.J)c=Math.min(c,a.n-(b>=0?b:b-1));else{d.length=c;if(b<0)return d}if(b<0)for(e=-b;e<=c;e+=1)d[e+b]=a.h[a.n-e];else for(e=b;e<b+c;e+=1)d[e-b]=a.h[e];return d}
function Lc(a,b){if(!a.content)return-1;var c,d;if(!b||!b.fa&&!b.t&&!b.g)return 0;a.ya||Gc(a);if(!a.J&&(b===Gb||!a.n||!(Hb(b,a.h[a.n-1].end)>=0))){Jc(a,[f,i,b]);return-1}if(b===Gb)return a.J?a.n-1:-1;c=0;for(d=a.n;c<d;c+=1)if(Hb(a.h[c].end,b)<0)return c;return a.J?a.n-1:-1};if(!Ra){var Mc=function(a){var b=[],c=[],d=[];d=[];d=u(a.childNodes);b=d.filter(function(e){return e.nodeType===1});if(C(a,"itemref")){d=a.getAttribute("itemref").trim().split(/\s+/);d.forEach(function(e){(e=document.getElementById(e))&&b.push(e)})}b=b.filter(function(e,g){var h=i,o=e,l=[];if(b.indexOf(e)!==g&&b.indexOf(e,g)!==-1)return k;for(;(o=o.parentNode)!==i&&o.nodeType===1;){l.push(o);if(C(o,"itemscope")){h=o;break}}if(h!==i){if(b.indexOf(h)!==-1)return k;return!l.some(function(j){var s=-1,
r=i;if((s=b.indexOf(j))!==-1){for(j=b[s];(j=j.parentNode)!==i&&j.nodeType===1;)if(C(j,"itemscope")){r=j;break}if(r===h)return f}return k})}return f});for(b.sort(function(e,g){return 3-((g.compareDocumentPosition?g.compareDocumentPosition(e):g.contains?(g!=e&&g.contains(e)&&16)+(g!=e&&e.contains(g)&&8)+(g.sourceIndex>=0&&e.sourceIndex>=0?(g.sourceIndex<e.sourceIndex&&4)+(g.sourceIndex>e.sourceIndex&&2):1)+0:0)&6)});a=b.pop();){if(C(a,"itemprop")){c.push(a);if(C(a,"itemscope")){a.itemScope=f;a.properties=
Mc(a)}}if(!C(a,"itemscope")){d=u(a.childNodes).reverse();d.forEach(function(e){e.nodeType===1&&b.push(e)})}}c.forEach(function(e){var g;if(C(e,"itemscope"))g=e;else{g=e.nodeName;g=g==="META"?e.content:["AUDIO","EMBED","IFRAME","IMG","SOURCE","VIDEO"].indexOf(g)!==-1?e.src:["A","AREA","LINK"].indexOf(g)!==-1?e.href:g==="OBJECT"?e.data:g==="TIME"&&C(e,"datetime")?e.dateTime:"textContent"in e?e.textContent:e.innerText}e.itemValue=g;e.itemProp=e.getAttribute("itemprop")});return c};document.getItems=
function(a,b){var c=[];a=a&&/\S/.test(a)?a.trim().split(/\s+/):[];b&&C(b,"itemscope")&&c.push(b);c=c.concat(ua("itemscope",i,i,b));return c=c.filter(function(d){if(!C(d,"itemprop")&&(a.length===0||C(d,"itemtype")&&a.indexOf(d.getAttribute("itemtype"))!==-1)){d.itemScope=f;d.properties=Mc(d);C(d,"itemid")&&(d.itemId=d.getAttribute("itemid"));C(d,"itemref")&&(d.itemRef=d.getAttribute("itemRef"));C(d,"itemtype")&&(d.itemType=d.getAttribute("itemtype"));return f}return k})}}
function Nc(a){var b={},c={},d={};if(a.itemType)b.type=a.itemType;if(a.itemId)b.id=a.itemId;if(C(a,"data-properties")){a.getAttribute("data-properties").split(/\s+/g).forEach(function(e){d[e]=f});b.flags=d}a.properties.forEach(function(e){var g=e.itemValue,h=[];g.itemScope&&(g=Nc(g));h=e.itemProp.split(/\s+/g);h.forEach(function(o){c[o]||(c[o]=[]);c[o].push(g)})});b.properties=c;return b}
function Oc(a,b){if(Ra){var c=u(document.getItems(a));if(!b)return c;return c.filter(function(d){return b.contains(d)})}else return document.getItems(a,b)}function rc(a){return Oc(i,a).map(function(b){return Nc(b)})}function sc(a){var b={},c;if(a.properties){c=Qb(a.properties);c.forEach(function(d){var e=a.properties[d][0];Object.prototype.toString.apply(e)==="[object Object]"&&(e=Eb.pc(e));b[d]=e})}return b};var Pc,Qc,Rc;function Sc(a){Rc=document.createElement("div");if(a){var b=document.createElement("div");b.style.display="none";Aa(b);b.innerHTML=a;u(b.childNodes).forEach(function(c){if(c.nodeType===1&&c.nodeName.toLowerCase()==="div")Rc.appendChild(c);else c.nodeType===1&&c.nodeName.toLowerCase()==="body"&&u(c.childNodes).forEach(function(d){d.nodeType===1&&d.nodeName.toLowerCase()==="div"&&Rc.appendChild(d)})});b.parentNode.removeChild(b);b.innerHTML=""}Tc()}
function Tc(){Pc=Uc;var a=Qc.slice(0);Qc=[];a.forEach(function(b){b()})}function Vc(a){return Rc?B(a,Rc):[]}var Uc=2;function Wc(a){return window.JSON.parse(a)}function Xc(a){return window.JSON.stringify(a)}if(!("JSON"in window)){Wc=function(a){try{return eval("("+a+")")}catch(b){}return i};Xc=function(){return""}};function Yc(a,b,c){c=c?window.localStorage:window.sessionStorage;c.getItem(a)&&c.removeItem(a);try{c.setItem(a,Xc(b))}catch(d){}}function Zc(a){return(a=window.sessionStorage.getItem(a)||window.localStorage.getItem(a))?Wc(a):i}function $c(a){window.sessionStorage.getItem(a)&&window.sessionStorage.removeItem(a);window.localStorage.getItem(a)&&window.localStorage.removeItem(a)}
function ad(a){var b=[],c,d,e,g;a=a||"";g=a.length;c=0;for(d=window.localStorage.length;c<d;c+=1)(e=window.localStorage.key(c))&&(!a||a===e.substr(0,g))&&b.push(window.localStorage.key(c));c=0;for(d=window.sessionStorage.length;c<d;c+=1){e=window.sessionStorage.key(c);b.indexOf(e)===-1&&(!a||a===e.substr(0,g))&&b.push(e)}return b}function bd(a,b){ad(a).forEach(function(c){(!b||b.indexOf(c)===-1)&&$c(c)})}
if(!Za){var ed={};Yc=function(a,b){ed[a]=b};Zc=function(a){return ed[a]};$c=function(a){delete ed[a]};ad=function(){return[]}};var R,S,T,U,fd,gd,hd,id,jd,kd,ld,md,nd,od,pd,qd,rd;function sd(a){S=R=i;T=-1;gd=fd=U=i;hd=[];id={};jd={};kd=[];ld=td();if(!ld)return k;ud();vd();md=F.ic(document.location.href);if(nd=a){a=new Cc(md,document.title,ld,a);if(a.error)wd();else{jd[md]=a;xd(a,i,0,f)}}yd.forEach(function(b){N(document,b,zd)});window.onpopstate=Ad;Bd();return f}function td(){var a=[];Vc("grid").forEach(function(b){var c=b.getAttribute("data-requires");if(!c||mb(c.split(" "))){b=new vc(b);b.error||a.push(b)}});return a}
function ud(){var a=Vc("loading")[0];a||(a=document.createElement("div"));document.body.appendChild(a);a.style.top="50%";K(a,"margin-top",-I(a)/2);document.body.removeChild(a);od=wa(a);a=a.cloneNode(f);document.body.appendChild(a);pd=new L(a);document.body.removeChild(a)}
function vd(){var a=Vc("error")[0];a||(a=document.createElement("div"));document.body.appendChild(a);a.style.top="50%";K(a,"margin-top",I(a)/2);document.body.removeChild(a);qd=wa(a);a=a.cloneNode(f);document.body.appendChild(a);rd=new L(a);document.body.removeChild(a)}function Cd(){pd=od=kd=jd=id=hd=fd=U=T=S=R=i;yd.forEach(function(a){Q(document,a,zd)});window.onpopstate=i}var yd=["treesaver.loaded","treesaver.loadfailed","treesaver.paginationprogress"];
function zd(a){if(a.type==="treesaver.paginationprogress")M(document,"treesaver.pageschanged");else if(a.type==="treesaver.loaded")M(document,"treesaver.pageschanged");else if(a.type==="treesaver.loadfailed"&&a.Q===R&&F.va())document.location=R.url}function Ad(a){if(a.state){var b=a.state.index;b||b===0?xd(hd[b],a.state.position,b,f):Dd(a.state.url)}else Dd(md)}
function Bd(){var a;a=ua("rel","contents","link")[0];a=!a||a.getAttribute("rel").indexOf("self")!==-1?md:F.Qa(a.href);a===md&&!(F.cb()&&F.va())?Ed(nd,a):F.get(a,Ed)}
function Ed(a,b){var c=b===md;if(a){Yc("cache:"+b,a,f);if(c&&F.cb()&&F.va()){Dc(R,a);M(document,"treesaver.pageschanged")}}else{a=Zc("cache:"+b);if(!a)return}var d=[];Fd(a);kd.forEach(function(e){var g,h,o;if(e.flags.self){g=b;e.H.url=b}else g=F.Qa(e.H.url);h=jd[g];o=hd.length;if(!h){h=new Cc(g,e.H.title||"",ld);jd[g]=h}if(id[g])id[g].push(o);else{id[g]=[o];d.push("cache:"+g);g===md&&(U=o)}hd.push(h)});bd("cache:",d);M(document,"treesaver.tocupdated")}
function Fd(a){var b=document.createElement("div"),c=[];b.className="offscreen";document.body.appendChild(b);b.innerHTML=a;c=rc(b);kd=c.map(function(d){var e=Qb(d.properties),g={H:{},flags:d.flags||{}};e.forEach(function(h){g.H[h]=d.properties[h][0]});return g});document.body.removeChild(b)}function Gd(){if(T===-1){if(!S&&Hd(f))return f;return k}var a=T-1;if(a<0){if(Hd(f))return f;return k}T=a;S=i;fd=-1;M(document,"treesaver.pageschanged");return f}
function Id(){if(T===-1){if(S===Gb&&Jd())return f;return k}var a=T+1;if(a>=R.n){if(R.J&&Jd())return f;return k}T=a;S=i;fd=1;M(document,"treesaver.pageschanged");return f}function Hd(a,b){if(!U)return i;var c=U-1,d=hd[c];return b?d:xd(d,a?Gb:i,c)}function Kd(){return!!((U||U===0)&&U<hd.length-1)}function Jd(a){if(!Kd())return i;var b=U+1,c=hd[b];return a?c:xd(c,i,b)}function Dd(a){a=Ld(a);if(!a&&a!==0)return k;return xd(hd[a],i,a)}
function Md(a){fd=0;if(Ic(R,a)){T=-1;gd=0}var b=[],c,d,e;if(T===-1){T=Lc(R,S);if(T===-1){b.length=3;b[1]=Nd();return b}}d=T-1;if(d<0){if((c=Hd(k,f))&&c.content&&c.J)b=Kc(c,d,-d);else{c=0;for(e=-d;c<e;c+=1)b[c]=i}c=3+d;d=0}else c=3;b=b.concat(Kc(R,d,c));if(c=3-b.length)if(d=Jd(f))if(d.content)b=b.concat(Kc(d,0,c));else{Od(d);Ic(d,a);b.length=3}c=1;for(e=b.length;c<e;c+=1)b[c]||(b[c]=R.error?{M:Bc.prototype.M,A:Bc.prototype.A,j:qd,size:rd}:Nd());if((!S||S===Gb)&&b[1]&&b[1].rb)S=b[1].rb;if(!gd)gd=R.ia?
R.ia.c:0;for(c=0;c<b.length;c+=1)for(a=c+1;a<b.length;a+=1)b[c]===b[a]&&(b[a]=b[c].F());return b}function Ld(a){a=id[a];var b,c;if(!a||!a.length)return i;else if(a.length===1)return a[0];else{for(b=a.length-1;b>=0;){c=a[b];if(c===U)break;if(c<U)break;b-=1}return c}}
function Od(a){if(!a.fb){a.fb=f;var b=Zc("cache:"+a.url);if(b){Dc(a,b);M(document,"treesaver.loaded",{Q:a})}F.get(a.url,function(c){a.fb=k;if(c){if(b!==c){Yc("cache:"+a.url,c,f);Dc(a,c);M(document,"treesaver.loaded",{Q:a})}}else if(!b){a.Zb=f;M(document,"treesaver.loadfailed",{Q:a})}})}}
function xd(a,b,c,d){if(!a)return k;if(R===a&&c===U)return f;if(a.title)document.title=a.title;R=a;if(S!==b){S=b;T=-1}T=-1;if(a.loaded){if(a.error){if(F.va())document.location=a.url;return k}}else Od(a);if(c||c===0){fd=U>c?-1:1;U=c}else{fd=0;U=Ld(a.url)}d?Pd({index:c,url:a.url,position:b},a.title,a.path):Qd({index:c,url:a.url,position:b},a.title,a.path);M(document,"treesaver.pageschanged");M(document,"treesaver.articlechanged",{Q:a,url:a.url,path:a.path});return f}
function Nd(){return{M:Bc.prototype.M,A:Bc.prototype.A,j:od,size:pd}};function Rd(a){this.a=a;this.Ba=a.firstChild}function Sd(a){a.Fb={c:J(a.a),b:I(a.a)};a.vb={c:J(a.Ba),b:I(a.Ba)};a.mb=a.mb||0;a.nb=a.nb||0;Td(a,0,0,f)}Rd.prototype.contains=function(a){return this.Ba.contains(a)};function Td(a,b,c,d){b={x:Math.max(0,Math.min(a.vb.c-a.Fb.c,a.mb+b)),y:Math.max(0,Math.min(a.vb.b-a.Fb.b,a.nb+c))};if(d){a.nb=b.y;a.mb=b.x}xb(a.Ba,-b.x,-b.y)}
function Ud(a){var b=document.createElement("div");v(b,"scroll-container");for(Na&&a.setAttribute("onclick","void(0)");a.firstChild;)b.appendChild(a.firstChild);a.appendChild(b)};function Vd(a){this.C=C(a,"data-requires")?a.getAttribute("data-requires").split(" "):i;B("scroll",a).forEach(Ud);this.Oa=[];this.a=i;this.j=a.parentNode.innerHTML;this.size=new L(a);delete this.size.c;delete this.size.b;this.wa=i;this.o=k;this.h=this.qb=this.P=this.jb=this.n=this.ib=this.z=i;this.qa=k;this.hb=i;this.O=k;this.Ka=this.La=this.Ia=this.nextPage=this.sidebar=this.Va=this.v=i}
Vd.prototype.M=function(){var a=[];a=[];a=[];if(!this.o){this.o=f;this.a=ya(this.j);this.z=B("viewer",this.a)[0];this.ib=Xb("pagenumber",this.a);this.n=Xb("pagecount",this.a);this.jb=B("pagewidth",this.a);this.Va=Xb("current-url",this.a);this.nextPage=B("next",this.a);this.Ia=B("nextArticle",this.a);this.La=B("prev",this.a);this.Ka=B("prevArticle",this.a);this.Oa=B("scroll",this.a).map(function(b){return new Rd(b)});a=B("menu",this.a);if(a.length>0)this.hb=a[0];a=Xb("toc",this.a);if(a.length>=1){this.P=
a[0];this.qb=this.P.cloneNode(f)}a=B("sidebar",this.a);if(a.length>0)this.sidebar=a[0];this.h=[];Wd.forEach(function(b){N(document,b,this)},this);this.qa=k;Xd(this)}return this.a};Vd.prototype.A=function(){if(this.o){Yd();this.o=k;Wd.forEach(function(a){Q(document,a,this)},this);this.Ka=this.La=this.Ia=this.nextPage=this.sidebar=this.qb=this.P=this.Va=this.hb=this.jb=this.n=this.ib=this.z=this.a=i;this.h.forEach(function(a){a&&a.A()});this.wa=this.h=i}};
function Yd(){ra("selectPages");ra("animatePages")}var Wd=["treesaver.tocupdated","treesaver.pageschanged","treesaver.articlechanged","keydown","click","mousewheel","DOMMouseScroll"];Na?Wd.push("touchstart","touchmove","touchend","touchcancel"):Wd.push("mouseover");
Vd.prototype.handleEvent=function(a){switch(a.type){case "treesaver.pageschanged":return Zd(this);case "treesaver.tocupdated":oa(this.Db,[],"updateTOC",this);return Zd(this);case "treesaver.articlechanged":$d(this);return ae(this,a);case "mouseover":a.touches||Xd(this);break;case "touchstart":return be(this,a);case "touchmove":if(this.e){a.stopPropagation();a.preventDefault();this.e.bb=m();this.e.Xb=a.touches[0].pageX;this.e.Yb=a.touches[0].pageY;this.e.Sb=this.e.bb-this.e.startTime;this.e.S=this.e.Xb-
this.e.fc;this.e.Da=this.e.Yb-this.e.hc;this.e.ea=Math.min(a.touches.length,this.e.ea);this.e.ob=this.e.ea===1&&Math.abs(this.e.S)>=30;if(this.e.Na)Td(this.e.Na,this.e.S,-this.e.Da);else if(this.e.ob){this.B=this.e.S;ce(this,f)}else if(this.B){this.Ra=m();ce(this,hb)}else if(this.e.ea===2)this.e.Wa=a.touches[1].pageX-this.e.gc}break;case "touchend":var b=this.e,c=k;qa();this.e=i;if(b){a.stopPropagation();a.preventDefault();if(b.Na&&b.bb)Td(b.Na,b.S,-b.Da,f);else if(b.ea===1)if(b.bb){if(b.ob||b.Da<=
-30)(c=b.ob&&b.S>0?Gd():Id())?this.V():Xd(this)}else{b=de(a.target);c=this.O||this.z.contains(b);var d=document.createEvent("MouseEvents");d.initMouseEvent("click",f,f,a.view,1,a.changedTouches[0].screenX,a.changedTouches[0].screenY,a.changedTouches[0].clientX,a.changedTouches[0].clientY,a.ctrlKey,a.altKey,a.shiftKey,a.metaKey,0,i);if(b.dispatchEvent(d)&&c)this.qa?this.V():Xd(this);else c?this.V():Xd(this);c=f}else if(b.ea===2&&Math.abs(b.Wa)>=30){if(b.S<0&&b.Wa<0)c=Jd();else b.S>0&&b.Wa>0&&(c=Hd());
c?this.V():Xd(this)}if(!c){this.Ra=m();this.B=0;ce(this,hb)}}break;case "touchcancel":qa();this.e=i;break;case "keydown":a:if(this.O){ee(this);a.preventDefault()}else if(!fe(a)){switch(a.keyCode){case 34:case 39:case 40:case 74:case 32:Id();break;case 33:case 37:case 38:case 75:Gd();break;case 72:Hd();break;case 76:Jd();break;default:c=void 0;break a}this.V();a.preventDefault()}return c;case "click":return this.click(a);case "mousewheel":case "DOMMouseScroll":if(fe(a))b=f;else if(this.O){ee(this);
a.preventDefault()}else{c=m();if(!(this.xb&&c-this.xb<1500)){this.xb=c;c=a.wheelDelta?a.wheelDelta:a.detail?-a.detail:0;d=this.z.contains(de(a.target));if(c&&d){a.preventDefault();a.stopPropagation();c>0?Gd():Id();this.V()}}}return b}};function fe(a){return a.ctrlKey||a.shiftKey||a.altKey||a.metaKey}
Vd.prototype.click=function(a){if(this.O){ee(this);a.stopPropagation();a.preventDefault()}else{if(fe(a))return f;if(!("which"in a&&a.which!==1||a.button)){var b=de(a.target),c,d=k,e=d=c=k;if(w(this.a,"menu-active")){e=this.hb.contains(b);sa(this.a,"menu-active")}if(ge(this))(d=this.sidebar.contains(b))||sa(this.a,"sidebar-active");if(this.h[0]&&this.h[0].a.contains(b)){Gd();c=f}else if(this.h[2]&&this.h[2].a.contains(b)){Id();c=f}else for(d=this.h[1]&&this.h[1].a.contains(b);!c&&b&&b!==W;){if(d)w(b,
"zoomable")&&(c=he(this,b));else if(w(b,"prev")){Gd();c=f}else if(w(b,"next")){Id();c=f}else if(w(b,"prevArticle")){Hd();c=f}else if(w(b,"nextArticle")){Jd();c=f}else if(w(b,"menu")){e||v(this.a,"menu-active");c=f}else if(w(b,"sidebar")||w(b,"open-sidebar")){ge(this)||v(this.a,"sidebar-active");c=f}else if(w(b,"close-sidebar")&&ge(this)){sa(this.a,"sidebar-active");c=f}if(!c&&b.href&&b.nodeName.toLowerCase()!=="img"){if(b.getAttribute("target")==="lightbox"){b=b.parentNode;continue}c=F.Qa(b.href);
if(!Dd(c))return;c=f}b=b.parentNode}if(c){a.stopPropagation();a.preventDefault()}}}};function de(a){if(a)a.nodeType!==1&&a.parentNode&&(a=a.parentNode||W);else a=W;return a}function be(a,b){if(W.contains(de(b.target))){b.stopPropagation();b.preventDefault();if(a.O)ee(a);else{a.e={startTime:m(),Sb:0,fc:b.touches[0].pageX,hc:b.touches[0].pageY,S:0,Da:0,ea:b.touches.length};if(a.e.ea===2)a.e.gc=b.touches[1].pageX;a.Oa.forEach(function(c){if(c.contains(de(b.target)))this.e.Na=c},a);pa([],4E3)}}}
function Xd(a){if(!a.qa){a.qa=f;v(a.a,"active");M(document,"treesaver.active")}var b=a.V,c=ga.idletimer;if(c)c.ab=m();else la(b,5E3,1,i,k,"idletimer",a)}Vd.prototype.V=function(){if(this.qa){this.qa=k;sa(this.a,"active");M(document,"treesaver.idle")}ra("idletimer")};function ge(a){return w(a.a,"sidebar-active")}
function he(a,b){var c;c=parseInt(b.getAttribute("data-figureindex"),10);c=isNaN(c)?i:R.content.l[c];if(!c)return k;a.V();if(!a.O){var d=ie(),e=je,g,h,o,l=i;g=0;for(h=e.length;g<h;g+=1){o=e[g];if(o.ca()&&o.Fa(d)){l=o;break}}a.v=l;if(!a.v)return k;a.O=f;a.v.M();a.a.parentNode.appendChild(a.v.a)}a.v.a=a.v.a;K(a.v.a,"width",J(a.a));K(a.v.a,"height",I(a.a));d=a.v;c=cc(c,{c:J(d.r),b:I(d.r)});e=J(d.r.offsetParent);g=I(d.r.offsetParent);d.r=d.r;if(d.o&&c){Ob(c.Ea,d.r,c.name);d.r.style.bottom="auto";d.r.style.right=
"auto";K(d.r,"left",(e-J(d.r))/2);K(d.r,"top",(g-I(d.r))/2);c=f}else c=k;if(!c){ee(a);return k}return f}function ee(a){if(a.O){a.O=k;a.a.parentNode.removeChild(a.v.a);a.v.A();a.v=i}}Vd.prototype.ca=function(){if(!this.C)return f;return mb(this.C,f)};Vd.prototype.Fa=function(a){return ub(this.size,a)};function ke(a){a.wa={c:J(a.z),b:I(a.z)}}function le(a,b){K(a.a,"width",b.c);K(a.a,"height",b.b);a.wa=i;ke(a);a.Oa.forEach(function(c){Sd(c)});if(R){Zd(a);oa(a.Db,[],"updateTOC",a)}}
function ae(a,b){a.Va.forEach(function(c){Sb({"current-url":b.url},c)})}function $d(a){if(a.P){var b=kd||[],c=Xb("article",a.P),d=0;b.forEach(function(e,g){if(!e.flags.hidden&&c[d]){g===U?v(c[d],"current"):sa(c[d],"current");d+=1}});a.Oa.forEach(function(e){Sd(e)})}}function me(a,b){a.ib.forEach(function(c){Sb({pagenumber:b},c)})}function ne(a,b){a.n.forEach(function(c){Sb({pagecount:b},c)})}function oe(a,b){b&&a.jb.forEach(function(c){K(c,"width",b)},a)}
function pe(a,b){if(a.nodeName==="BUTTON")a.disabled=!b;else b?sa(a,"disabled"):v(a,"disabled")}function qe(a){if(a.nextPage){var b=T!==-1?T<R.n-1?f:R.J&&Kd():S===Gb?Kd():k;a.nextPage.forEach(function(c){pe(c,b)},a)}}function re(a){if(a.Ia){var b=Kd();a.Ia.forEach(function(c){pe(c,b)},a)}}function se(a){if(a.La){var b=T!==-1?T>=1?f:!!U:!S&&!!U;a.La.forEach(function(c){pe(c,b)},a)}}function te(a){if(a.Ka){var b=!!U;a.Ka.forEach(function(c){pe(c,b)},a)}}function Zd(a){oa(a.Cb,[],"selectPages",a)}
Vd.prototype.Cb=function(){Yd();var a=fd;ue(this,a);var b=this.h[0],c=this.h[1],d=this.h[2],e,g=Math.max(c.size.marginRight,d?d.size.marginLeft:0),h=Math.max(c.size.marginLeft,b?b.size.marginRight:0),o=this.B;c.a.setAttribute("id","currentPage");e=(this.wa.c-c.size.oa)/2-g;c=e+c.size.oa+g+h;this.U=[];this.U[1]=e;if(b){this.U[0]=e-(b.size.oa+b.size.marginLeft);b.a.setAttribute("id","previousPage")}if(d){this.U[2]=c-d.size.marginLeft;d.a.setAttribute("id","nextPage")}if(a!==0){this.Ra=m();this.B=a===
-1?d?this.U[1]-this.U[2]:0:b?this.U[1]-this.U[0]:0;o&&(this.B+=o)}else if(!this.B)this.B=0;if(hb&&this.B)this.B=0;ce(this,hb);me(this,T+1||1);ne(this,R.n||1);oe(this,gd);qe(this);re(this);se(this);te(this)};
Vd.prototype.Db=function(){ra("updateTOC");if(this.P){var a=kd||[],b=this.qb.cloneNode(f),c=this.P.parentNode;a=a.filter(function(d){return!d.flags.hidden});a=a.map(function(d){return{article:d.H}});Rb({toc:a},b);c.replaceChild(b,this.P);this.P=b;M(document,"treesaver.articlechanged",{Q:R,url:R.url,path:R.path})}};
function ue(a,b){var c=a.h;a.h=Md(a.wa);c.forEach(function(d){if(d&&this.h.indexOf(d)===-1){d.a&&d.a.parentNode===this.z&&this.z.removeChild(d.a);d.A()}},a);a.h.forEach(function(d){if(d){d.a||d.M();d.a.parentNode!==this.z&&(b===-1?this.z.insertBefore(d.a,this.z.firstChild):this.z.appendChild(d.a))}},a)}
function ce(a,b){var c=a.B;if(!b){pa(["animatePages"],400);var d=m();c*=-Math.cos((!b?Math.max(0,(a.Ra||0)+200-d)/200:1)*Math.PI)/2+0.5;if(Math.abs(c)<5){a.B=c=0;qa()}else oa(a.Cb,[],"animatePages",a)}a.h.forEach(function(e,g){e&&e.a&&yb(e.a,this.U[g]+c)},a)};function ve(a){B("container",a);this.C=C(a,"data-requires")?a.getAttribute("data-requires").split(" "):i;this.j=a.parentNode.innerHTML;this.size=new L(a);delete this.size.c;delete this.size.b;this.o=k;this.r=this.a=i}ve.prototype.M=function(){if(!this.o){this.o=f;this.a=ya(this.j);this.r=B("container",this.a)[0]}return this.a};ve.prototype.A=function(){if(this.o){this.o=k;this.a=i}};ve.prototype.Fa=function(a){return ub(this.size,a)};
ve.prototype.ca=function(){if(!this.C)return f;return mb(this.C,f)};var X,we,je;function xe(){X={orientation:0,size:{c:0,b:0}};va(W);X.ha=ye();X.Eb=ze();we=Ae();je=Be();if(!we.length)return k;Ce();na(Ce,[],"checkState");if(Ma&&!De){N(window,"orientationchange",Ee);ma(function(){window.scrollTo(0,1)},100)}return f}function ye(){if(De)return W;else{var a=document.createElement("div");a.setAttribute("id","chromeContainer");W.appendChild(a);return a}}
function ze(){var a=ua("name","viewport","meta")[0];if(!a){a=document.createElement("meta");a.setAttribute("name","viewport");ta("head")[0].appendChild(a)}return a}function Ae(){var a=[];Vc("chrome").forEach(function(b){var c;c=b.getAttribute("data-requires");if(!(c&&!mb(c.split(" ")))){X.ha.appendChild(b);c=new Vd(b);a.push(c);X.ha.removeChild(b)}});return a}
function Be(){var a=[];Vc("lightbox").forEach(function(b){var c;c=b.getAttribute("data-requires");if(!(c&&!mb(c.split(" ")))){X.ha.appendChild(b);c=new ve(b);a.push(c);X.ha.removeChild(b)}});return a}function Ee(){if(X.orientation!==window.orientation){jb();X.orientation=window.orientation;X.orientation%180?X.Eb.setAttribute("content","width=device-height, height=device-width"):X.Eb.setAttribute("content","width=device-width, height=device-height");window.scrollTo(0,1)}}
function ie(){if(De)return{c:J(W),b:I(W)};else{(window.pageYOffset||window.pageXOffset)&&window.scrollTo(0,1);return"innerWidth"in window?{c:window.innerWidth,b:window.innerHeight}:{c:document.documentElement.clientWidth,b:document.documentElement.clientHeight}}}
function Ce(){var a=ie(),b;if(a.b!==X.size.b||a.c!==X.size.c){X.size=a;if(!X.R||!X.R.ca()||!X.R.Fa(a)){b=we;var c,d,e,g=i;c=0;for(d=b.length;c<d;c+=1){e=b[c];if(e.ca()&&e.Fa(a)){g=e;break}}b=g;if(!b)return;va(X.ha);X.R&&X.R.A();X.ha.appendChild(b.M());X.R=b}le(X.R,a)}};function wd(){Q(window,"unload",wd);Cd();Ma&&!De&&Q(window,"orientationchange",Ee);X.R&&X.R.A();je=we=X=i;Fe()};var Y={};Y.ja={Pa:"treesaver.ready"};Y.dc=function(){return Y.Xa};Y.loaded=function(){return Y.Tb};Y.Xa=k;Y.Tb=k;Y.Ma=function(){if(!Y.Xa)if(document.body){Y.Xa=f;Q(document,"DOMContentLoaded",Y);Q(document,"readystatechange",Y);Q(window,"load",Y);delete Y.Ya;M(document,Y.ja.Pa)}else oa(Y.Ma)};Y.kb=function(){if("readyState"in document)/complete|loaded/.test(document.readyState)&&Y.Ma();else{var a=document.getElementsByTagName("*").length;if(Y.Ya)a===Y.Ya&&Y.Ma();else{Y.Ya=a;ma(Y.kb,100)}}};
Y.handleEvent=function(a){/load|DOMContentLoaded/.test(a.type)?Y.Ma():Y.kb()};N(document,"DOMContentLoaded",Y);N(document,"readystatechange",Y);N(window,"load",Y);Y.kb();var Ge={"treesaver-init":{target:"treesaver-init-0.9.2.js",src:"init.js"},"treesaver-core":{target:"treesaver-core-0.9.2.js",src:"core.js"}};Ge.get=function(a){return Ge[a].target};Ge.get("treesaver-init");var W,De,He,Ie,Je,Ke;function Fe(){if(De)W.innerHTML=Je;else if(He)W.innerHTML=He;Le();ka();Rc=i;Pc=0;Qc=[];F.kc();document.documentElement.className="js no-treesaver";document.documentElement.style.display="block"}function Le(){ra("unboot");Q(document,Y.ja.Pa,Me);delete Ie;delete Ke}
function Me(){Ke=f;if(W=document.getElementById("ts_container")){De=f;Je=W.innerHTML}else{De=k;W=document.body}He=document.body.innerHTML;va(W);W.innerHTML='<div id="loading">Loading '+document.title+"...</div>";document.documentElement.style.display="block";Ne()}function Ne(){if(Ie&&Ke&&document.body){Le();N(window,"unload",wd);xe()&&sd(He)||wd()}};var Oe,Pe="pushState"in window.history;function Qe(){var a=document.location.href.indexOf("#");return a===-1?"":document.location.href.substr(a+1)}if(document.location.hash){var Re=Qe();Re.charAt(0)==="-"&&Re.length>=2&&document.location.replace(Re.substr(1))}function Qd(a,b,c){window.history.pushState(a,b,c)}function Pd(a,b,c){window.history.replaceState(a,b,c)}
if(!Pe){Qd=function(a,b,c){Se(a,b,c,k)};Pd=function(a,b,c){Se(a,b,c,f)};var Te=function(a){document.location.hash="#"+a},Ue=function(a){document.location.replace("#"+a)},Se=function(a,b,c,d){var e="-"+window.escape(c);Yc("history:"+e,{state:a,title:b});c===document.location.pathname&&(e="");Oe=e;d?Ue(e):Te(e)},Ve=function(){var a=Qe();if(a!==Oe){a=(Oe=a)?Zc("history:"+a):{};"onpopstate"in window&&typeof window.onpopstate==="function"&&window.onpopstate.apply(window,[{state:a?a.state:i}])}},We=function(){return Qe()!==
Oe};if("onhashchange"in window&&!Ea)window.onhashchange=Ve;else{na(function(){We()&&Ve()});if(Ia==="msie"){var Xe=document.createElement("iframe");Aa(Xe);We=function(){var a=Xe.contentWindow.document.body.innerHTML;if(a!==Oe){document.location.hash="#"+(a||"");return f}};Ue=function(a){var b=Xe.contentWindow.document;if(a!==b.body.innerHTML)b.body.innerHTML=a;document.location.replace("#"+a)};Te=function(a){var b=Xe.contentWindow.document;b.open();b.write("<html><body>"+a+"</body></html>");b.close();
document.location.hash="#"+a}}}};eval("/*@cc_on (function(a,b,c){while(b--)a.createElement(c[b])})(document,21,['abbr','article','aside','audio','canvas','details','figcaption','figure','footer','header','hgroup','mark','menu','meter','nav','output','progress','section','summary','time','video'])@*/");/*
 Copyright 2011 Filipe Fortes ( www.fortes.com ).
 Version: 0.1.

 Licensed under MIT and GPLv2.
*/
if(Da){document.documentElement.style.display="none";F.load();jb();var Ye=function(){Ie=f;Ne()},Ze;a:{var $e=document.getElementsByTagName("link"),af,bf=$e.length;for(af=0;af<bf;af+=1)if($e[af].rel.toLowerCase().indexOf("resources")!==-1){Ze=$e[af].getAttribute("href");break a}Ze=i}if(Ze)if(Pc)Pc===Uc?Ye():Qc.push(Ye);else{Pc=1;Qc=[Ye];F.get(Ze,Sc)}else Ye();Y.dc()?Me():N(document,Y.ja.Pa,Me);ma(Fe,5E3,[],"unboot")}ca("treesaver.VERSION","0.9.2-0-g3228db8",void 0);}());
